### ISSUE TITLE
CTR-V 1.1.7 seems very broken

### ISSUE THREAD

**Issue by Noahkiq** [initPRAGMA/CTR-V#2]
Clicking "connect" to connect to your 3DS successfully opens up NTR Viewer and starts a stream, but this error pops up.

![image](https://cloud.githubusercontent.com/assets/13265322/21290810/c55b76a2-c496-11e6-96e3-cf19ab3b6c34.png)

The "Send Memory Patch" button also prints "Connected" to the output log, then does nothing, which makes games like Pokemon X/Y unstreamable.

**Comment by initPRAGMA** [comment]
Can you copy and paste the Details.

**Comment by Noahkiq** [comment]
Uploaded the error to [pastebin](http://pastebin.com/raw/z0YiSuAz)

**Comment by initPRAGMA** [comment]
Can you tell me the exact steps your doing to get this error?
Start from you having your 3DS just turned on.

**Comment by Noahkiq** [comment]
Turned 3DS on -> Opened NTR 3.4 using Boot NTR Selector

On PC: Opened CTR-V -> Clicked "Connect" -> Accepted UAC Prompt -> error message appears shortly after NTR viewer opens

**Comment by initPRAGMA** [comment]
Try running CTR-V as an admin. Probs wont do anything, Also, Make sure your 3DS is connected to Internet on top left before connecting

LMK the results

**Comment by Noahkiq** [comment]
Already said the 3DS was connected to the internet when I said the program successfully connects to the 3DS and starts an NTR Viewer stream.

Running the program as admin makes the error not appear when connected, but the memory patch button still just prints `Connected` then doesn't properly disconnect. (clicking `Disconnect` also does nothing)

Though, I did just realize the memory patch button still patches the game. Guess this update is less broken than I originally thought.

**Comment by initPRAGMA** [comment]
So running as an admin fixed the popup error message?
And yeah I probably just forgot to tell it to output that it wrote the mempatch

**Comment by Noahkiq** [comment]
Yep, running as admin fixed the error message

**Comment by initPRAGMA** [comment]
Thats that sorted then :3
